from tkinter import *
root=Tk()
root.geometry("340x370")
root.title("calculator")
root.resizable(0,0)
text=StringVar()
frame=Frame(root,width=312,height=50,highlightbackground="purple",highlightthickness=2)
frame.pack(side="top")
input=Entry(frame,font="arial 18",width=30,textvariable=text,bg="lightgrey",bd=8,justify=RIGHT)
input.grid()
input.pack(ipady=10)
btn_frame=Frame(root,width=312,height=300,bg="grey")
btn_frame.pack()
def clr():
    text.set("")
def onclick(num):
    text.set(text.get()+num)
def equal():
    ent=text.get()
    text.set(eval(ent))
clr=Button(btn_frame,text="C",width=34,height=3,bd=3,fg="black",bg="lightgreen",command=clr)
clr.grid(row=0,column=0,columnspan=3,padx=1,pady=1)
div=Button(btn_frame,text="/",fg='black',bg="lightgreen",bd=3,width=10,height=3,command=lambda:onclick("/"))
div.grid(row=0,column=3,padx=1,pady=1)
seven=Button(btn_frame,text="7",width=10,height=3,bd=3,fg="black",bg="skyblue",command=lambda:onclick("7"))
seven.grid(row=1,column=0,padx=1,pady=1)
eight=Button(btn_frame,text="8",width=10,height=3,bd=3,fg="black",bg="skyblue",command=lambda:onclick("8"))
eight.grid(row=1,column=1,padx=1,pady=1)
nine=Button(btn_frame,text="9",width=10,height=3,bd=3,fg="black",bg="skyblue",command=lambda:onclick("9"))
nine.grid(row=1,column=2,padx=1,pady=1)
mul=Button(btn_frame,text="X",width=10,height=3,bd=3,fg="black",bg="skyblue",command=lambda:onclick("*"))
mul.grid(row=1,column=3,padx=1,pady=1)
four=Button(btn_frame,text="4",width=10,height=3,bd=3,fg="black",bg="skyblue",command=lambda:onclick("7"))
four.grid(row=2,column=0,padx=1,pady=1)
five=Button(btn_frame,text="5",width=10,height=3,bd=3,fg="black",bg="skyblue",command=lambda:onclick("5"))
five.grid(row=2,column=1,padx=1,pady=1)
six=Button(btn_frame,text="6",width=10,height=3,bd=3,fg="black",bg="skyblue",command=lambda:onclick("6"))
six.grid(row=2,column=2,padx=1,pady=1)
minus=Button(btn_frame,text="-",width=10,height=3,bd=3,fg="black",bg="skyblue",command=lambda:onclick("-"))
minus.grid(row=2,column=3,padx=1,pady=1)
one=Button(btn_frame,text="1",width=10,height=3,bd=3,fg="black",bg="skyblue",command=lambda:onclick("1"))
one.grid(row=3,column=0,padx=1,pady=1)
two=Button(btn_frame,text="2",width=10,height=3,bd=3,fg="black",bg="skyblue",command=lambda:onclick("2"))
two.grid(row=3,column=1,padx=1,pady=1)
three=Button(btn_frame,text="3",width=10,height=3,bd=3,fg="black",bg="skyblue",command=lambda:onclick("3"))
three.grid(row=3,column=2,padx=1,pady=1)
add=Button(btn_frame,text="+",width=10,height=3,bd=3,fg="black",bg="skyblue",command=lambda:onclick("+"))
add.grid(row=3,column=3,padx=1,pady=1)
zero = Button(btn_frame,text="0",fg ="black",width=23,height=3,bd=3,bg ="skyblue",cursor="hand2",command=lambda:onclick("0")).grid(row=4,column=0,columnspan=2,padx=1,pady=1)
point=Button(btn_frame,text=".",fg ="black",width=10,height=3,bd=3,bg="skyblue",cursor="hand2",command=lambda:onclick(".")).grid(row=4,column=2,padx=1,pady=1)
equals=Button(btn_frame,text="=",fg ="black",width=10,height=3,bd=3,bg="skyblue",cursor="hand2",command=equal).grid(row=4,column=3,padx=1,pady=1)
root.mainloop()
